const CATEGORY_RULES: [RegExp, string][] = [
  [/\.pdf$/i, "documents"],
  [/\.docx?$/i, "documents"],
  [/\.xlsx?$/i, "documents"],
  [/\.pptx?$/i, "documents"],
  [/\.txt$/i, "documents"],
  [/\.rtf$/i, "documents"],
  [/\.csv$/i, "documents"],
  [/\.md$/i, "documents"],
  [/\.json$/i, "documents"],
  [/\.xml$/i, "documents"],
  [/\.html?$/i, "documents"],
  [/\.jpg$/i, "images"],
  [/\.jpeg$/i, "images"],
  [/\.png$/i, "images"],
  [/\.gif$/i, "images"],
  [/\.svg$/i, "images"],
  [/\.webp$/i, "images"],
  [/\.bmp$/i, "images"],
  [/\.ico$/i, "images"],
  [/\.heic$/i, "images"],
  [/\.mp4$/i, "videos"],
  [/\.mov$/i, "videos"],
  [/\.avi$/i, "videos"],
  [/\.mkv$/i, "videos"],
  [/\.webm$/i, "videos"],
  [/\.wmv$/i, "videos"],
  [/\.mp3$/i, "audio"],
  [/\.wav$/i, "audio"],
  [/\.flac$/i, "audio"],
  [/\.aac$/i, "audio"],
  [/\.ogg$/i, "audio"],
  [/\.wma$/i, "audio"],
  [/\.m4a$/i, "audio"],
  [/\.zip$/i, "archives"],
  [/\.tar$/i, "archives"],
  [/\.gz$/i, "archives"],
  [/\.rar$/i, "archives"],
  [/\.7z$/i, "archives"],
  [/\.iso$/i, "archives"],
  [/\.dmg$/i, "archives"],
  [/\.exe$/i, "executables"],
  [/\.msi$/i, "executables"],
  [/\.sh$/i, "executables"],
  [/\.bat$/i, "executables"],
  [/\.app$/i, "executables"],
  [/\.dll$/i, "executables"],
  [/\.so$/i, "executables"],
  [/\.cert$/i, "certificates"],
  [/\.pem$/i, "certificates"],
  [/\.crt$/i, "certificates"],
  [/\.key$/i, "certificates"],
  [/\.pfx$/i, "certificates"],
  [/\.p12$/i, "certificates"],
  [/\.p7b$/i, "certificates"],
  [/\.ics$/i, "calendar"],
  [/\.vcf$/i, "contacts"],
  [/\.sig$/i, "signatures"],
  [/\.pgp$/i, "signatures"],
  [/\.gpg$/i, "signatures"],
];

export function categorizeByFilename(filename: string): string {
  for (const [pattern, category] of CATEGORY_RULES) {
    if (pattern.test(filename)) return category;
  }
  return "uncategorized";
}

const KEYWORD_EXTRACTORS: [RegExp, string][] = [
  [/invoice/i, "invoice"],
  [/receipt/i, "receipt"],
  [/statement/i, "statement"],
  [/contract/i, "contract"],
  [/agreement/i, "contract"],
  [/bill/i, "bill"],
  [/order/i, "order"],
  [/confirmation/i, "confirmation"],
  [/ticket/i, "ticket"],
  [/booking/i, "booking"],
  [/reservation/i, "booking"],
  [/report/i, "report"],
  [/presentation/i, "presentation"],
  [/photo/i, "photo"],
  [/screenshot/i, "screenshot"],
  [/scan/i, "scan"],
  [/resume/i, "resume"],
  [/cv$/i, "resume"],
  [/curriculum/i, "resume"],
  [/cover.?letter/i, "cover_letter"],
  [/offer.?letter/i, "offer_letter"],
  [/tax/i, "tax"],
  [/w2/i, "tax"],
  [/1099/i, "tax"],
  [/paystub/i, "paystub"],
  [/pay.?slip/i, "paystub"],
  [/signature/i, "signature"],
  [/nda/i, "nda"],
  [/proposal/i, "proposal"],
  [/quote/i, "quote"],
  [/estimate/i, "estimate"],
  [/policy/i, "policy"],
  [/license/i, "license"],
  [/certification/i, "certification"],
  [/diploma/i, "diploma"],
  [/transcript/i, "transcript"],
  [/menu/i, "menu"],
  [/newsletter/i, "newsletter"],
  [/catalog/i, "catalog"],
  [/brochure/i, "brochure"],
  [/flyer/i, "flyer"],
  [/poster/i, "poster"],
  [/map/i, "map"],
  [/drawing/i, "drawing"],
  [/blueprint/i, "blueprint"],
  [/diagram/i, "diagram"],
  [/schedule/i, "schedule"],
  [/roster/i, "roster"],
  [/timesheet/i, "timesheet"],
  [/expense/i, "expense"],
  [/budget/i, "budget"],
  [/financial/i, "financial"],
  [/bank/i, "financial"],
];

export function extractKeywordsForCategory(filename: string): string[] {
  const keywords: string[] = [];
  for (const [pattern, keyword] of KEYWORD_EXTRACTORS) {
    if (pattern.test(filename) && !keywords.includes(keyword)) {
      keywords.push(keyword);
    }
  }
  return keywords;
}
