use std::fs;
use std::io::Write;
use std::path::PathBuf;

#[derive(serde::Deserialize)]
struct CampaignData {
    name: String,
    total_sent: u32,
    unique_opens: u32,
    total_clicks: u32,
    bounced_count: u32,
    open_rate: f64,
    click_rate: f64,
    bounce_rate: f64,
    daily_stats: Vec<DailyStat>,
    top_links: Vec<LinkStat>,
}

#[derive(serde::Deserialize)]
struct DailyStat {
    date: String,
    opens: u32,
    clicks: u32,
}

#[derive(serde::Deserialize)]
struct LinkStat {
    url: String,
    clicks: u32,
}

#[tauri::command]
pub fn export_analytics_report(campaign_data: String) -> Result<String, String> {
    let data: CampaignData =
        serde_json::from_str(&campaign_data).map_err(|e| format!("Invalid campaign data: {e}"))?;

    let report_dir = get_report_dir()?;
    let filename = format!(
        "campaign_report_{}.html",
        chrono::Local::now().format("%Y%m%d_%H%M%S")
    );
    let filepath = report_dir.join(&filename);

    let html = build_html_report(&data);
    let mut file =
        fs::File::create(&filepath).map_err(|e| format!("Failed to create file: {e}"))?;
    file.write_all(html.as_bytes())
        .map_err(|e| format!("Failed to write file: {e}"))?;

    Ok(filepath.to_string_lossy().to_string())
}

fn get_report_dir() -> Result<PathBuf, String> {
    let dir = dirs::document_dir()
        .ok_or_else(|| "Could not find documents directory".to_string())?
        .join("Velo")
        .join("reports");
    fs::create_dir_all(&dir).map_err(|e| format!("Failed to create report directory: {e}"))?;
    Ok(dir)
}

fn build_html_report(data: &CampaignData) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Campaign Report - {name}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1a1a1a; max-width: 800px; margin: 0 auto; }}
h1 {{ font-size: 24px; margin-bottom: 4px; }}
.meta {{ color: #666; margin-bottom: 32px; }}
.stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }}
.stat-card {{ border: 1px solid #e5e5e5; border-radius: 8px; padding: 16px; }}
.stat-label {{ font-size: 12px; color: #666; }}
.stat-value {{ font-size: 28px; font-weight: 700; margin-top: 4px; }}
table {{ width: 100%; border-collapse: collapse; margin-bottom: 24px; }}
th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #e5e5e5; font-size: 14px; }}
th {{ background: #f5f5f5; font-weight: 600; }}
.r0 {{ color: #059669; }}
.r1 {{ color: #d97706; }}
.r2 {{ color: #dc2626; }}
.footer {{ margin-top: 32px; color: #999; font-size: 11px; text-align: center; }}
</style>
</head>
<body>
<h1>Campaign Report</h1>
<p class="meta">{name}</p>
<div class="stats">
<div class="stat-card"><div class="stat-label">Total Sent</div><div class="stat-value">{total_sent}</div></div>
<div class="stat-card"><div class="stat-label">Unique Opens</div><div class="stat-value">{unique_opens}</div></div>
<div class="stat-card"><div class="stat-label">Total Clicks</div><div class="stat-value">{total_clicks}</div></div>
<div class="stat-card"><div class="stat-label">Bounced</div><div class="stat-value">{bounced_count}</div></div>
</div>
<table>
<tr><th>Metric</th><th>Value</th></tr>
<tr><td>Open Rate</td><td class="r0">{open_rate_pct}%</td></tr>
<tr><td>Click Rate</td><td class="r1">{click_rate_pct}%</td></tr>
<tr><td>Bounce Rate</td><td class="r2">{bounce_rate_pct}%</td></tr>
</table>
{daily_table}
{links_table}
<p class="footer">Generated by Velo Mail</p>
</body>
</html>"#,
        name = data.name,
        total_sent = data.total_sent,
        unique_opens = data.unique_opens,
        total_clicks = data.total_clicks,
        bounced_count = data.bounced_count,
        open_rate_pct = format_rate(data.open_rate),
        click_rate_pct = format_rate(data.click_rate),
        bounce_rate_pct = format_rate(data.bounce_rate),
        daily_table = build_daily_table(&data.daily_stats),
        links_table = build_links_table(&data.top_links),
    )
}

fn format_rate(rate: f64) -> String {
    format!("{:.1}", rate * 100.0)
}

fn build_daily_table(stats: &[DailyStat]) -> String {
    if stats.is_empty() {
        return String::new();
    }
    let rows: Vec<String> = stats
        .iter()
        .map(|d| {
            format!(
                "<tr><td>{}</td><td>{}</td><td>{}</td></tr>",
                d.date, d.opens, d.clicks
            )
        })
        .collect();
    format!(
        "<h2>Engagement Over Time</h2>\n<table>\n<tr><th>Date</th><th>Opens</th><th>Clicks</th></tr>\n{}</table>",
        rows.join("\n")
    )
}

fn build_links_table(links: &[LinkStat]) -> String {
    if links.is_empty() {
        return String::new();
    }
    let rows: Vec<String> = links
        .iter()
        .map(|l| {
            let display = if l.url.len() > 60 {
                format!("{}...", &l.url[..57])
            } else {
                l.url.clone()
            };
            format!("<tr><td>{}</td><td>{}</td></tr>", display, l.clicks)
        })
        .collect();
    format!(
        "<h2>Top Links</h2>\n<table>\n<tr><th>URL</th><th>Clicks</th></tr>\n{}</table>",
        rows.join("\n")
    )
}
